// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopService is the sole Wails binding surface for the restored Vue app.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

/**
 * Call dispatches the historical request envelope to a registered Go service.
 */
export function Call(request: contracts$0.GatewayRequest): $CancellablePromise<any> {
    return $Call.ByID(1653902428, request);
}

export function Capabilities(): $CancellablePromise<contracts$0.ApplicationCapabilities> {
    return $Call.ByID(121040602).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = contracts$0.ApplicationCapabilities.createFrom;
