// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ApplicationCapabilities {
    "updates": boolean;

    /** Creates a new ApplicationCapabilities instance. */
    constructor($$source: Partial<ApplicationCapabilities> = {}) {
        if (!("updates" in $$source)) {
            this["updates"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationCapabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplicationCapabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplicationCapabilities($$parsedSource as Partial<ApplicationCapabilities>);
    }
}

/**
 * GatewayRequest is the single Wails binding method input. Params intentionally
 * remains an object so the facade can preserve every historical argument shape.
 */
export class GatewayRequest {
    "method": RequestMethod;
    "params": any;

    /** Creates a new GatewayRequest instance. */
    constructor($$source: Partial<GatewayRequest> = {}) {
        if (!("method" in $$source)) {
            this["method"] = RequestMethod.$zero;
        }
        if (!("params" in $$source)) {
            this["params"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayRequest($$parsedSource as Partial<GatewayRequest>);
    }
}

/**
 * RequestMethod keeps the legacy frontend request names stable while the Go
 * services are ported incrementally behind one Wails gateway.
 */
export enum RequestMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RequestGetAccounts = "getAccounts",
    RequestGetSettings = "getSettings",
    RequestSaveSettings = "saveSettings",
    RequestGetUserAliases = "getUserAliases",
    RequestSetUserAlias = "setUserAlias",
    RequestRemoveUserAlias = "removeUserAlias",
    RequestGetChannels = "getChannels",
    RequestAuthStart = "authStart",
    RequestAuthLogout = "authLogout",
    RequestJoinChannel = "joinChannel",
    RequestLeaveChannel = "leaveChannel",
    RequestSendMessage = "sendMessage",
    RequestGetStreamStatus = "getStreamStatus",
    RequestUpdateStream = "updateStream",
    RequestSearchCategories = "searchCategories",
    RequestGetChannelsStatus = "getChannelsStatus",
    RequestGetRecentMessages = "getRecentMessages",
    RequestGetUserChatHistory = "getUserChatHistory",
    RequestGetUserCardMetadata = "getUserCardMetadata",
    RequestGetStatuses = "getStatuses",
    RequestGetUsernameColor = "getUsernameColor",
    RequestGetChannelEmotes = "getChannelEmotes",
    RequestCheckForUpdate = "checkForUpdate",
    RequestDownloadUpdate = "downloadUpdate",
    RequestApplyUpdate = "applyUpdate",
    RequestSkipUpdate = "skipUpdate",
    RequestGetWatchedChannels = "getWatchedChannels",
    RequestAddWatchedChannel = "addWatchedChannel",
    RequestRemoveWatchedChannel = "removeWatchedChannel",
    RequestGetWatchedChannelMessages = "getWatchedChannelMessages",
    RequestSendWatchedChannelMessage = "sendWatchedChannelMessage",
    RequestGetWatchedChannelStatuses = "getWatchedChannelStatuses",
    RequestOpenExternalURL = "openExternalUrl",
    RequestGetTabChannelIDs = "getTabChannelIds",
    RequestSetTabChannelIDs = "setTabChannelIds",
    RequestGetWatchedChannelsLayout = "getWatchedChannelsLayout",
    RequestSetWatchedChannelsLayout = "setWatchedChannelsLayout",
    RequestRemovePanel = "removePanel",
    RequestAssignChannelToPanel = "assignChannelToPanel",
    RequestSplitPanel = "splitPanel",
};
